version: "3"

services:
  keycloak:
    container_name: keycloak-auth
    image: quay.io/keycloak/keycloak:21.0.2
    command: [start-dev, --http-port=8080, --import-realm]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: preview
    networks:
      - localhost
    ports:
      - '8080:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./import/realm-export.json:/opt/keycloak/data/import/realm.json
      - ./import/custom-keycloak-theme.jar:/opt/keycloak/providers/custom-keycloak-theme.jar
      - ./import/custom-registration.jar:/opt/keycloak/providers/custom-registration.jar:ro
networks:
  localhost:
    driver: bridge
